"""Add bookmarks table

Revision ID: 72e248caceb0
Revises: fefdc7cca132
Create Date: 2025-11-12 10:43:23.175767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e248caceb0'
down_revision = 'fefdc7cca132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='unique_user_post_bookmark')
    )
    op.add_column('likes', sa.Column('reaction_type', sa.String(length=20), nullable=True))
    op.create_unique_constraint('unique_user_comment_reaction', 'likes', ['user_id', 'comment_id', 'reaction_type'])
    op.create_unique_constraint('unique_user_post_reaction', 'likes', ['user_id', 'post_id', 'reaction_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_post_reaction', 'likes', type_='unique')
    op.drop_constraint('unique_user_comment_reaction', 'likes', type_='unique')
    op.drop_column('likes', 'reaction_type')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
