name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change if you want deployments from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Zip application
        run: |
          zip -r app.zip . -x "*.git*" "*__pycache__*" "*.github*" "*.venv*" "venv/*" "instance/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: The-national-cake-community
          environment_name: The-national-cake-community-env-1
          version_label: v-${{ github.run_number }}
          region: eu-west-1
          deployment_package: app.zip
